<?php

namespace ErrorWatch\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('error_watch');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode('enabled')
                    ->defaultFalse()
                    ->info('Enable/disable ErrorWatch. Accepts bool or env var (e.g. %env(bool:ERRORWATCH_ENABLED)%).')
                ->end()
                ->scalarNode('endpoint')
                    ->defaultValue('')
                    ->info('ErrorWatch API endpoint URL')
                ->end()
                ->scalarNode('api_key')
                    ->defaultValue('')
                    ->info('ErrorWatch API key')
                ->end()
                ->scalarNode('environment')
                    ->defaultValue('')
                    ->info('Environment name (defaults to kernel.environment)')
                ->end()
                ->scalarNode('release')
                    ->defaultNull()
                    ->info('Release version (e.g., "1.2.3"). Auto-detects from git if not set.')
                ->end()
                ->arrayNode('replay')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->booleanNode('debug')->defaultFalse()->info('Enable verbose console logging for replay debugging')->end()
                        ->floatNode('sample_rate')
                            ->defaultValue(0.1)
                            ->min(0.0)
                            ->max(1.0)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('breadcrumbs')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->info('Enable automatic breadcrumb collection')->end()
                        ->integerNode('max_count')
                            ->defaultValue(100)
                            ->min(1)
                            ->max(500)
                            ->info('Maximum number of breadcrumbs to keep')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('user_context')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->info('Enable user context capture for error attribution')->end()
                        ->booleanNode('capture_ip')
                            ->defaultTrue()
                            ->info('Capture IP address in user context')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('console')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('capture_exit_codes')->defaultTrue()
                            ->info('Capture non-zero exit codes even without exceptions')->end()
                    ->end()
                ->end()
                ->arrayNode('messenger')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('capture_retries')->defaultFalse()
                            ->info('Also capture failures that will be retried (noisy)')->end()
                    ->end()
                ->end()
                ->arrayNode('deprecations')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()
                            ->info('Capture PHP deprecations (opt-in, can be noisy)')->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('capture_login_success')->defaultFalse()
                            ->info('Add breadcrumbs for successful logins')->end()
                    ->end()
                ->end()
                ->arrayNode('apm')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('request_tracking')->defaultTrue()->end()
                        ->arrayNode('doctrine')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                                ->booleanNode('log_queries')->defaultTrue()->info('Log sanitized SQL in span descriptions')->end()
                            ->end()
                        ->end()
                        ->arrayNode('http_client')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                                ->booleanNode('capture_errors_as_breadcrumbs')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->integerNode('n_plus_one_threshold')
                            ->defaultValue(5)
                            ->min(2)
                            ->info('Minimum repeated query count to flag as N+1')
                        ->end()
                        ->integerNode('slow_query_threshold_ms')
                            ->defaultValue(500)
                            ->min(1)
                            ->info('Query duration threshold in ms to flag as slow')
                        ->end()
                        ->arrayNode('excluded_routes')
                            ->scalarPrototype()->end()
                            ->defaultValue(['_profiler', '_wdt'])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('monolog')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->info('Enable automatic Monolog forwarding to ErrorWatch')->end()
                        ->enumNode('level')
                            ->values(['debug', 'info', 'notice', 'warning', 'error', 'critical', 'alert', 'emergency'])
                            ->defaultValue('warning')
                        ->end()
                        ->arrayNode('excluded_channels')
                            ->scalarPrototype()->end()
                            ->defaultValue(['event', 'doctrine', 'http_client'])
                            ->info('Monolog channels ignored by the ErrorWatch handler')
                        ->end()
                        ->booleanNode('capture_context')->defaultTrue()->info('Include Monolog context in payload')->end()
                        ->booleanNode('capture_extra')->defaultTrue()->info('Include Monolog extra data in payload')->end()
                    ->end()
                ->end()
                ->arrayNode('logs')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->info('Enable live log streaming to /api/v1/logs')->end()
                        ->enumNode('level')
                            ->values(['debug', 'info', 'notice', 'warning', 'error', 'critical', 'alert', 'emergency'])
                            ->defaultValue('debug')
                        ->end()
                        ->arrayNode('excluded_channels')
                            ->scalarPrototype()->end()
                            ->defaultValue(['event', 'doctrine', 'http_client'])
                            ->info('Monolog channels ignored by the live logs handler')
                        ->end()
                        ->booleanNode('capture_context')->defaultTrue()->info('Include Monolog context in live logs payload')->end()
                        ->booleanNode('capture_extra')->defaultTrue()->info('Include Monolog extra data in live logs payload')->end()
                    ->end()
                ->end()
            ->end();

        $rootNode
            ->validate()
                ->ifTrue(static function (array $config): bool {
                    $enabled = $config['enabled'] ?? true;
                    // Skip validation when enabled is an env var placeholder (resolved at runtime)
                    if (\is_string($enabled) && str_contains($enabled, '%env(')) {
                        return false;
                    }
                    $active = filter_var($enabled, FILTER_VALIDATE_BOOLEAN)
                        || (($config['replay']['enabled'] ?? false) === true);

                    return $active && ($config['endpoint'] ?? '') === '';
                })
                ->thenInvalid('error_watch.endpoint is required when error_watch is enabled.')
            ->end()
            ->validate()
                ->ifTrue(static function (array $config): bool {
                    $enabled = $config['enabled'] ?? true;
                    if (\is_string($enabled) && str_contains($enabled, '%env(')) {
                        return false;
                    }
                    $active = filter_var($enabled, FILTER_VALIDATE_BOOLEAN)
                        || (($config['replay']['enabled'] ?? false) === true);

                    return $active && ($config['api_key'] ?? '') === '';
                })
                ->thenInvalid('error_watch.api_key is required when error_watch is enabled.')
            ->end();

        return $treeBuilder;
    }
}
