<?php

namespace ContainerN1wyqBm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorSenderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Makfly\ErrorMonitoringBundle\Service\ErrorSender' shared autowired service.
     *
     * @return \Makfly\ErrorMonitoringBundle\Service\ErrorSender
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/Service/ErrorSenderInterface.php';
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/Service/ErrorSender.php';
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/Http/MonitoringClientInterface.php';
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/Http/MonitoringClient.php';
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/Service/LevelMapper.php';

        return $container->privates['Makfly\\ErrorMonitoringBundle\\Service\\ErrorSender'] = new \Makfly\ErrorMonitoringBundle\Service\ErrorSender(true, 'dev', '1.0.0-demo', new \Makfly\ErrorMonitoringBundle\Http\MonitoringClient('http://localhost:3333', 'ew_live_T4cBfRJ6oGvQi5uXBfcMp9OayyZF0dHF', ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'))), new \Makfly\ErrorMonitoringBundle\Service\LevelMapper());
    }
}
