<?php

namespace ContainerN1wyqBm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Makfly\ErrorMonitoringBundle\EventSubscriber\ExceptionSubscriber' shared autowired service.
     *
     * @return \Makfly\ErrorMonitoringBundle\EventSubscriber\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/packages/error-monitoring-bundle/src/EventSubscriber/ExceptionSubscriber.php';

        return $container->privates['Makfly\\ErrorMonitoringBundle\\EventSubscriber\\ExceptionSubscriber'] = new \Makfly\ErrorMonitoringBundle\EventSubscriber\ExceptionSubscriber(($container->privates['Makfly\\ErrorMonitoringBundle\\Service\\ErrorSender'] ?? $container->load('getErrorSenderService')));
    }
}
