<?php

namespace ContainerN1wyqBm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateErrorsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateErrorsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateErrorsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-errors', [], 'Generate test errors for ErrorWatch dashboard testing', false, #[\Closure(name: 'App\\Command\\GenerateErrorsCommand')] fn (): \App\Command\GenerateErrorsCommand => ($container->privates['App\\Command\\GenerateErrorsCommand'] ?? $container->load('getGenerateErrorsCommandService')));
    }
}
