<?php

namespace ContainerN1wyqBm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateErrorsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateErrorsCommand' shared autowired service.
     *
     * @return \App\Command\GenerateErrorsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateErrorsCommand.php';

        $container->privates['App\\Command\\GenerateErrorsCommand'] = $instance = new \App\Command\GenerateErrorsCommand(($container->privates['Makfly\\ErrorMonitoringBundle\\Service\\ErrorSender'] ?? $container->load('getErrorSenderService')));

        $instance->setName('app:generate-errors');
        $instance->setDescription('Generate test errors for ErrorWatch dashboard testing');

        return $instance;
    }
}
