<?php

namespace ContainerN1wyqBm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TestController' shared autowired service.
     *
     * @return \App\Controller\TestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TestController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ECommerce/OrderService.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/OrderRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Mock/DatabaseConnection.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ECommerce/InventoryService.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ECommerce/PaymentService.php';
        include_once \dirname(__DIR__, 4).'/src/Gateway/Payment/PaymentGatewayInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Gateway/Payment/StripeGateway.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ECommerce/ShippingService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Database/DatabaseService.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/UserRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Api/ExternalApiClient.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Auth/AuthenticationService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Auth/JwtService.php';

        $a = new \App\Repository\Mock\DatabaseConnection();

        $b = new \App\Repository\OrderRepository($a);
        $c = new \App\Repository\ProductRepository($a);
        $d = new \App\Repository\UserRepository($a);

        $container->services['App\\Controller\\TestController'] = $instance = new \App\Controller\TestController(new \App\Service\ECommerce\OrderService($b, new \App\Service\ECommerce\InventoryService($c), new \App\Service\ECommerce\PaymentService(new \App\Gateway\Payment\StripeGateway(), $b), new \App\Service\ECommerce\ShippingService()), new \App\Service\Database\DatabaseService($a, $d, $b), new \App\Service\Api\ExternalApiClient(), new \App\Service\Auth\AuthenticationService($d, new \App\Service\Auth\JwtService()), $c, $d, $a);

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'twig' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\TestController', $container));

        return $instance;
    }
}
